### ISSUE TITLE
Is it possible to display help when no argument is passed to the script

### ISSUE THREAD

**Issue by statquant** [trevorld/r-optparse#38]
Hello, I was trying to make sure the usage of a Rscript is displayed when no argument is passed the the script, similarily to when -h or --help is passed.
I did not find anything, is it possible ?
I understand it might not be doable because there are legitimate cases where no argument is expected behavior

**Comment by trevorld** [comment]
You'd have to do this manually (since yes, there are legitimate cases where no argument is expected behavior).  ``base::commandArgs(trailing=TRUE)`` will let you know if any arguments was passed to the script and ``optparse::print_help()``can be used to print the usage at any time.  So something like the following should work:

```
library(optparse)
parser = OptionParser()
if (length(commandArgs(TRUE)) == 0) {
  print_help(parser)
  quit(status = 0)
}
```

**Comment by trevorld** [comment]
Alternatively, if you expect at least one "positional" argument you could set the ``positional_arguments`` argument in ``parse_args`` to ``c(1, Inf)``, then ``parse_args`` will throw an error if there are no "positional" arguments passed to the script.  You could then catch the error and instead ``print_help``.

**Comment by statquant** [comment]
That works,thank you for your prompt answer
